# Generated by Django 5.1.4 on 2025-03-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_journalprompt_journalentry_journalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='tags',
        ),
    ]
