# Generated by Django 5.1.4 on 2025-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_moodentry_sentiment_score_moodentry_mood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodentry',
            old_name='date',
            new_name='date_logged',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='mood_category',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='mood_score',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='category',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default='Neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'happy'), ('excited', 'excited'), ('grateful', 'grateful'), ('content', 'content'), ('hopeful', 'hopeful'), ('proud', 'proud'), ('relaxed', 'relaxed'), ('loved', 'loved'), ('confident', 'confident'), ('energetic', 'energetic'), ('optimistic', 'optimistic'), ('relieved', 'relieved'), ('calm', 'calm'), ('bored', 'bored'), ('indifferent', 'indifferent'), ('tired', 'tired'), ('okay', 'okay'), ('apathetic', 'apathetic'), ('unsure', 'unsure'), ('blank', 'blank'), ('sad', 'sad'), ('angry', 'angry'), ('stressed', 'stressed'), ('frustrated', 'frustrated'), ('anxious', 'anxious'), ('guilty', 'guilty'), ('lonely', 'lonely'), ('hopeless', 'hopeless'), ('overwhelmed', 'overwhelmed'), ('disappointed', 'disappointed')], max_length=50),
        ),
    ]
