# Generated by Django 5.1.7 on 2025-04-05 18:35

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_date_moodentry_date_logged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('PSY', 'Psychiatrist'), ('CLP', 'Clinical Psychologist'), ('CP', 'Counseling Psychologist'), ('SW', 'Clinical Social Worker'), ('MFT', 'Marriage & Family Therapist'), ('LPC', 'Licensed Professional Counselor'), ('ART', 'Art Therapist'), ('MHC', 'Mental Health Counselor')], max_length=3)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_state', models.CharField(max_length=50)),
                ('therapeutic_approaches', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('profile_complete', models.BooleanField(default=False)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('qualifications', models.TextField()),
                ('areas_of_focus', models.TextField(help_text='Specific mental health conditions or populations you specialize in')),
                ('practice_name', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('accepts_insurance', models.BooleanField(default=False)),
                ('sliding_scale', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.CharField(max_length=20)),
                ('session_format', models.CharField(choices=[('INP', 'In-person'), ('ONL', 'Online'), ('BOTH', 'Both')], max_length=100)),
                ('session_length', models.PositiveIntegerField(default=50, help_text='Typical session length in minutes')),
                ('session_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee per session in your local currency', max_digits=6)),
                ('availability', models.TextField(help_text='Your typical availability (e.g., Mon-Wed 9am-5pm)')),
                ('profile_picture', models.ImageField(blank=True, upload_to='therapists/profile_pics/')),
                ('license_verification', models.FileField(upload_to='therapists/license_docs/')),
                ('crisis_protocol', models.TextField(blank=True, help_text='Your protocol for handling client crises')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mental_health_pro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
