# Generated by Django 5.1.7 on 2025-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_appointment_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='birth_date',
            new_name='age',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
