# Generated by Django 5.1.7 on 2025-04-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_birth_date_patientprofile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='about',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
