# Generated by Django 5.1.7 on 2025-04-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_about_patientprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
