# Generated by Django 5.1.7 on 2025-04-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_patientprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
    ]
