# Generated by Django 5.1.7 on 2025-04-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_patientprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
