# Generated by Django 5.1.7 on 2025-05-07 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_appointment_reschedule_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('care_team', 'Visible to Care Team'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientProfessionalRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_mood', models.BooleanField(default=True)),
                ('access_journal', models.BooleanField(default=False)),
                ('journal_access_level', models.CharField(choices=[('summary', 'Only Sentiment Summary'), ('titles', 'Entry Titles Only'), ('full', 'Full Journal Access')], default='summary', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_team', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'professional')},
            },
        ),
    ]
