# Generated by Django 5.1.7 on 2025-05-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_patientprofessionalrelationship_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofessionalrelationship',
            name='tatus',
        ),
    ]
