# Generated by Django 5.1.7 on 2025-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_patientprofessionalrelationship_tatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofessionalrelationship',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
