# Generated by Django 5.1.7 on 2025-05-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_appointment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthprofessional',
            name='license_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealthprofessional',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealthprofessional',
            name='therapeutic_approaches',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
